// <auto-generated />
namespace CIT275_Back_end_interface.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class client2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(client2));
        
        string IMigrationMetadata.Id
        {
            get { return "201704070345191_client2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
