// <auto-generated />
namespace CIT275_Back_end_interface.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cl));
        
        string IMigrationMetadata.Id
        {
            get { return "201703210227212_cl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
